# Generated by Django 6.0.4 on 2026-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_options_customuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
